from typing import Protocol
from dataclasses import dataclass

class ConfigInfo(Protocol):
    @property
    def soft_block_spawn_chance(self) -> int: ...
    @property
    def powerup_spawn_chance(self) -> int: ...
    @property
    def timer_seconds(self) -> int: ...
    @property
    def num_human_players(self) -> int: ...
    @property
    def num_bots(self) -> int: ...
    @property
    def bot_types(self) -> list[str] | None: ...
    @property
    def rounds_to_win(self) -> int: ...

@dataclass
class Settings:
    ...