from __future__ import annotations
from typing import Protocol, TypeVar, runtime_checkable
from enum import Enum, StrEnum, auto


# new types for readabilityy

class EntityType(StrEnum):
    EXPLOSION = auto()
    BOMB = auto()
    BLOCK = auto()
    PLAYER = auto()
    POWERUP = auto()

class SoundType(Enum):
    EXPLOSION = auto()
    POWERUP_GET = auto()
    # ... to add

# note: inaassume lang neto that we have only one entity per grid
T = TypeVar("T", bound=EntityInfo)
type Board = list[list[EntityInfo | None]]
type GridCoords = tuple[int, int]

class Direction(Enum):
    NORTH = (-1, 0)
    SOUTH = (1, 0)
    EAST = (0, 1)
    WEST = (0, -1)


class ExplosionOrientation(Enum):
    CENTER = auto() # cross type sprite or smthing
    VERTICAL = auto() # vertical
    HORIZONTAL = auto() # horizontal


# Updates and Events

class EventInfo(Protocol):
    def execute(self, world: WorldInfo) -> None: ...

class UpdateResultInfo(Protocol):
    @property
    def events(self) -> list[EventInfo]: ...
    @property
    def sounds(self) -> list[SoundType]: ...
    def add_event(self, cmd: EventInfo): ...
    def add_sound(self, cmd: SoundType): ...

# The World

class WorldInfo(Protocol):
    @property
    def rows(self) -> int: ...
    @property
    def cols(self) -> int: ...
    @property
    def entities(self) -> set[EntityInfo]: ...
    @property
    def board(self) -> Board: ...
    def add_entity(self, entity: EntityInfo) -> None: ...
    def remove_entity(self, entity: EntityInfo) -> None: ...
    def get_entity_at(self, i: int, j: int) -> EntityInfo | None: ...
    def get_all_type(self, entity_type: type[T]) -> set[T]: ...
    def is_cell_blocking(self, row: int, col: int) -> bool: ...
    def in_bounds(self, i: int, j: int) -> bool: ...
    
class EntityInfo(Protocol):
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...

    @property
    def entity_type(self) -> EntityType: ...
    def on_explosion_hit(self) -> None: ...
    def update(self, dt: int) -> UpdateResultInfo: ...


# ENTITIES:

@runtime_checkable
class ExplosionInfo(Protocol):
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...

    _full_timer: int # PRIVATE: we store the full duration of an explosion to last
    
    @property
    def current_timer(self) -> int: ...

    @property
    def entity_type(self) -> EntityType: ...
    @property
    def is_expired(self) -> bool: ...
    def on_explosion_hit(self) -> None: ...
    def update(self, dt: int) -> UpdateResultInfo: ...

@runtime_checkable
class BombInfo(Protocol):
    move_away_ids: set[int]
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...

    _full_timer: int # PRIVATE: we store the full countdown till the bomb explodes

    @property
    def current_timer(self) -> int: ...
    @property
    def owner(self) -> PlayerInfo: ...

    @property
    def should_detonate(self) -> bool: ...
    def get_affected_cells(self) -> list[GridCoords]: ...
    # ^^^ for explosion calculation and danger sensing para sa mga enemies
    
    @property
    def entity_type(self) -> EntityType: ...
    @property
    def is_expired(self) -> bool: ...
    def on_explosion_hit(self) -> None: ...
    def update(self, dt: int) -> UpdateResultInfo: ...
    @property
    def explosion_range(self) -> int: ...
    def create_explosions(self, world: WorldInfo, result: UpdateResultInfo): ...


@runtime_checkable
class BlockInfo(Protocol):
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...

    # note, create two subclasses for BlockInfo
    #   1. Hard (should have `pass` under `on_explosion_hit`)
    #   2. Soft
    @property
    def entity_type(self) -> EntityType: ...
    @property
    def is_expired(self) -> bool: ...
    def on_explosion_hit(self) -> None: ...
    def update(self, dt: int) -> UpdateResultInfo: ...
    @property
    def is_hard(self)-> bool: ...

@runtime_checkable
class PlayerInfo(Protocol):
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...
    @property
    def id(self) -> int:...
    
    # need to store x and y, but idk if this violates LSP? ;-; what's an alternative..
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def hitbox_x(self) -> float: ...
    @property
    def hitbox_y(self) -> float: ...
    @property
    def speed(self) -> float: ...
    @property
    def direction_facing(self) -> Direction: ...

    def move(self, direction: Direction) -> int: ...
    def decide_move(self) -> Direction: ... # for AI
    def set_speed(self, ds: int): ...
    def remove(self, bomb: BombInfo): ...
    def add(self, bomb: BombInfo): ...

    @property
    def entity_type(self) -> EntityType: ...
    @property
    def is_expired(self) -> bool: ...
    def on_explosion_hit(self) -> None: ...
    def update(self, dt: int) -> UpdateResultInfo: ...

@runtime_checkable
class PowerupInfo(Protocol):
    ... # to implement pahelp lang hehe
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...

    @property
    def entity_type(self) -> EntityType: ...
    @property
    def is_expired(self) -> bool: ...
    def on_explosion_hit(self) -> None: ...
    def update(self, dt: int) -> UpdateResultInfo: ...


# NON-ENTITIES:

class BotAIInfo(Protocol):
    # methods that will be useful for the AI's decision making
    def get_visible_distance(self) -> set[GridCoords]: ... # manhattan distance
    def get_shortest_path(self, goal: GridCoords) -> tuple[GridCoords]: ... # dijkstras algo
    def get_next_input(self) -> Direction | None: ...

