
from common_types import GridCoords


# TEMPORARY; TO IMPLEMENT!
class AttackPolicy1:
    def __init__(self, reachable_only: bool, max_distance: int): ...
    def get_goal(self) -> GridCoords | None: ...
class AttackPolicy2:
    # def __init__(self, reachable_only: bool, max_distance: int): ...
    def get_goal(self) -> GridCoords | None: ...
class PowerupPolicy1:
    def get_goal(self) -> GridCoords | None: ...
class PowerupPolicy2:
    def get_goal(self) -> GridCoords | None: ...


class BombOnlyDangerPolicy:
    def is_in_danger(self) -> bool: ...

class ExplosionPredictionDangerPolicy:
    def is_in_danger(self) -> bool: ...
# TEMPORARY; TO IMPLEMENT!